const data = {
    products: [
        {
            name: "PlayStation 3",
            category: "console, playstation",
            image: "/images/ps3.png",
            price: 499,
            countInStock: 10,
        },
        {
            name: "Xbox 360",
            category: "console, xbox",
            image: "/images/wii.png",
            price: 299,
            countInStock: 10,
        },
        {
            name: "Wii",
            category: "console, nintendo",
            image: "/images/xbox-360.png",
            price: 249,
            countInStock: 10,
        },
        {
            name: "Wii",
            category: "console, nintendo",
            image: "/images/xbox-360.png",
            price: 249,
            countInStock: 10,
        },
        {
            name: "Wii",
            category: "console, nintendo",
            image: "/images/xbox-360.png",
            price: 249,
            countInStock: 10,
        },
        {
            name: "Wii",
            category: "console, nintendo",
            image: "/images/xbox-360.png",
            price: 249,
            countInStock: 10,
        },
        {
            name: "Wii",
            category: "console, nintendo",
            image: "/images/xbox-360.png",
            price: 249,
            countInStock: 10,
        },
        {
            name: "Wii",
            category: "console, nintendo",
            image: "/images/xbox-360.png",
            price: 249,
            countInStock: 10,
        },
        {
            name: "Wii",
            category: "console, nintendo",
            image: "/images/xbox-360.png",
            price: 249,
            countInStock: 10,
        },
        {
            name: "Wii",
            category: "console, nintendo",
            image: "/images/xbox-360.png",
            price: 249,
            countInStock: 10,
        },
        {
            name: "Wii",
            category: "console, nintendo",
            image: "/images/xbox-360.png",
            price: 249,
            countInStock: 10,
        },
        {
            name: "Wii",
            category: "console, nintendo",
            image: "/images/xbox-360.png",
            price: 249,
            countInStock: 10,
        },
        {
            name: "Wii",
            category: "console, nintendo",
            image: "/images/xbox-360.png",
            price: 249,
            countInStock: 10,
        },
        {
            name: "Wii",
            category: "console, nintendo",
            image: "/images/xbox-360.png",
            price: 249,
            countInStock: 10,
        },
        {
            name: "Wii",
            category: "console, nintendo",
            image: "/images/xbox-360.png",
            price: 249,
            countInStock: 10,
        },
        {
            name: "Wii",
            category: "console, nintendo",
            image: "/images/xbox-360.png",
            price: 249,
            countInStock: 10,
        },
        {
            name: "Wii",
            category: "console, nintendo",
            image: "/images/xbox-360.png",
            price: 249,
            countInStock: 10,
        },
        {
            name: "Wii",
            category: "console, nintendo",
            image: "/images/xbox-360.png",
            price: 249,
            countInStock: 10,
        },
        {
            name: "Wii",
            category: "console, nintendo",
            image: "/images/xbox-360.png",
            price: 249,
            countInStock: 10,
        },
    ],
};
export default data;
